baseurl = "/"
defaultContentLanguage = "en"
destination = "../dist/"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableEmoji = true
hrefTargetBlank = false
languageCode = "en-us"
languageLang = "en"
relativeURLs = false
title = "My New Hugo Site"
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 3
[[menu.main]]
name = "About"
url = "/about"
weight = 2
[[menu.main]]
name = "Work"
url = "/work"
weight = 1
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[params]
author = "Nick Mason"
description = "The web portfolio of Nick Mason, a Product Design Leader who is not the drummer from Pink Floyd."
